
// Objective-C API for talking to the following Go packages
//
//	github.com/pion-bridge/server/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __PionBridgeGo_FRAMEWORK_H__
#define __PionBridgeGo_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
