// Objective-C API for talking to github.com/pion-bridge/server/mobile Go package.
//   gobind -lang=objc github.com/pion-bridge/server/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileStartResult;

/**
 * StartResult holds the listening port and session token after a successful Start().
 */
@interface MobileStartResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long port;
@property (nonatomic) NSString* _Nonnull token;
@end

/**
 * Start starts the PionBridge WebSocket server on an ephemeral loopback port.
Returns port and token that the Dart layer uses to connect.
Calling Start() while already running returns an error.
 */
FOUNDATION_EXPORT MobileStartResult* _Nullable MobileStart(NSError* _Nullable* _Nullable error);

/**
 * Stop stops the PionBridge server. Safe to call when not running.
 */
FOUNDATION_EXPORT BOOL MobileStop(NSError* _Nullable* _Nullable error);

#endif
